import { Inter } from "next/font/google";
import "./globals.css";
import FontAwesome from "./fontawesome";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Suranga Senanayake",
  description: "Generated by southwind Global",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <FontAwesome />
      </head>
      <body className={`${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
