import { Inter } from "next/font/google";
import "./globals.css";
import FontAwesome from "./fontawesome";
import { Toaster } from 'react-hot-toast';

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Suranga Senanayake",
  description: "Generated by southwind Global",
  icons: {
    icon: "/icon.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <FontAwesome />
      </head>
      <body className={inter.className}>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
